#
#' Draw Molecule by `rcdk` Defined by SMILES
#'
#'
#' @family Visualization and Graphics
#'
#'
#' @description
#'   A short description...
#'
#'
#'
#' @param molecules Character vector => either vector of molecular SMILES strings (in case
#'   of \code{type = "smiles"}/\code{type = "SMILES"}) or vector of file path strings
#'   (generated by e.g. \code{\link{list.files}}) pointing to \code{".sdf"} files.
#' @param type Character string ...tbc... either \code{type = "smiles"}/\code{type = "SMILES"}
#'   or \code{type = "sdf"}/\code{type = "SDF"}. \strong{Default}: \code{type = "smiles"}.
#' @param mol.names Character vector pointing to name of molecules/compounds, e.g. like
#'   \code{mol.names = c("acetone")} or \code{mol.names = c("PBN","DMPO")}.
#' @param mol.names.color Character string pointing to displayed font color of the chemical structure
#'   name. \strong{Default}: \code{mol.names.color = "black"}.
#' @param sma Character string allowing to highlight sub-structures using `SMARTS`
#'   (\strong{SM}ILES \strong{A}rbitrary \strong{T}arget \strong{S}pecification) to highlight
#'   common substructures in a set of molecules, e.g. like \code{sma = "C=O"}.
#' @param annotate Character string, whether to display (\code{annotate = "number"}) or do not display
#'   (\code{annotate = "off"}) atomic numbers/indexes. \strong{Default}: \code{annotate = "off"}.
#' @param style Character string denoting the plotting style like =>
#'   \tabular{rcl}{
#'   ----------------  \tab ----------------------------- \cr
#'   \strong{Plotting Style} \tab \strong{Style Text String} \cr
#'   ----------------  \tab ----------------------------- \cr
#'   `color on black`  \tab \code{style = "cob"} \cr
#'   `color on white`  \tab \code{style = "cow"} \cr
#'   `black on white`  \tab \code{style = "bow"} \cr
#'   `white on black` \tab \code{style = "wob"} \cr
#'   `neon on black`  \tab \code{style = "nob"} \cr
#'   ---------------- \tab ----------------------------- \cr
#'   }
#'   \strong{Default}: \code{style = "cow"}.
#' @param abbr Character string which controls how the structure is displayed. Following options
#'   can be set => \code{abbr = "off"} (\strong{default}) pointing to present structure as is;
#'   \code{abbr = "groups"} creating an abbreviation for `groups`; \code{abbr = "reagents"} creating
#'   an abbreviation for `reagents` or \code{abbr = "on"} to abbreviate the both latter.
#'   The \code{abbr = "groups"} WORKS ONLY IF \code{annotate = "of"}!
#' @param suppressh Logical, denoting whether to suppress displaying the hydrogen atoms.
#'   The `smiles` or `sdf` STRUCTURE MUST CONTAIN \strong{H} ATOMS!
#'   \strong{Default}: \code{supressh = TRUE}.
#' @param ... Additional options/arguments for \code{\link[rcdk]{get.depictor}}.
#'
#'
#' @return
#' tbc
#'
#' @examples
#' \dontrun{
#' tbc
#' tbc
#' }
#'
#' @export
#'
#'
#' @importFrom rcdk get.depictor view.image.2d load.molecules  parse.smiles
#' @importFrom graphics rasterImage text par
#' @importFrom stringr str_detect regex
## function to plot molecules inspired by https://riveradelgado.com/post/2021/04/18/chemistry-in-r/,
## which is not available in `rcdk`
draw_molecules_by_rcdk <- function(molecules,
                                   type = "smiles", ## or "sdf"
                                   mol.names = NULL,
                                   mol.names.color = "black",
                                   sma = NULL,
                                   annotate = "off",
                                   style = "cow",
                                   abbr = "off",
                                   suppressh = TRUE,
                                   ...){
  ## molecules is string vector, however it is converted into an object
  ## as returned by rcdk::load.molecules or rcdk::parse.smiles() => see below;
  ## name a character for the name of the molecule,
  ## sma a character witht the smarts string as passed onto get.depictor()
  ## ... other arguments for get.depictor()
  ##
  # Image aesthetics `depictor`
  dep <- rcdk::get.depictor(
    width = 600,
    height = 400,
    zoom = 6,
    sma = sma,
    annotate = annotate,
    style = style,
    abbr = abbr,
    suppressh = suppressh,
    ...
  )
  #
  ## load molecular types
  if (stringr::str_detect(type,stringr::regex("SMILES",ignore_case = TRUE))){
    #
    molekels <- rcdk::parse.smiles(molecules)
  }
  if (stringr::str_detect(type,stringr::regex("SDF",ignore_case = TRUE))){
    #
    ## create a list similar as in the previous case
    molekels <- rcdk::load.molecules(molfiles = molecules)
  }
  #
  ## molecules for the entire list
  molecules_sdf <- c()
  for (i in seq(molekels)){
    molecules_sdf[[i]] <- rcdk::view.image.2d(molekels[[i]],depictor = dep)
  }
  #
  ## Remove extra margins around the molecule
  graphics::par(mar = c(0,0,0,0))
  plot(NA,
       xlim = c(1, 10),
       ylim = c(1, 10),
       ## Remove the black bounding boxes around the molecule
       axes = FALSE)
  #
  ## draw and annotate molecules
  for (i in seq(molekels)){
    graphics::rasterImage(molecules_sdf[[i]], 1,1, 10,10)
    #
    ## drawing test based on `mol.names`
    if (is.null(mol.names)){
      graphics::text(x = 5.5,
                     y = 1.1,
                     labels = c("mol. structure viewer"),
                     col = "gray")
    } else{
      graphics::text(x = 5.5,
                     y = 1.1,
                     labels = mol.names[[i]],
                     col = mol.names.color)
    }
    #
  }
  #
}
