#
#' Draw Molecule by `rcdk` Defined by SMILES
#'
#'
#' @family Visualization and Graphics
#'
#'
#' @description
#'   A short description...
#'
#'
#'
#' @param molecules Character vector => either vector of molecular SMILES strings (in case
#'   of \code{type = "smiles"}/\code{type = "SMILES"}) or vector of file path strings
#'   (generated by e.g. \code{\link{list.files}}) pointing to \code{".sdf"} files
#' @param type Character string ...tbc... either \code{type = "smiles"}/\code{type = "SMILES"}
#'   or \code{type = "sdf"}/\code{type = "SDF"}
#' @param name tbc
#' @param sma tbc
#' @param ... tbc
#'
#'
#' @return
#' tbc
#'
#' @examples
#' \dontrun{
#' tbc
#' tbc
#' }
#'
#' @export
#'
#'
#' @importFrom rcdk get.depictor view.image.2d load.molecules  parse.smiles
#' @importFrom graphics rasterImage text par
#' @importFrom stringr str_detect regex
## function to plot molecules inspired by https://riveradelgado.com/post/2021/04/18/chemistry-in-r/,
## which is not available in `rcdk`
draw_molecules_rcdk <- function(molecules,
                                type = "smiles", ## or "sdf"
                                name = NULL,
                                sma = NULL,
                                ...){
  ## molecules is string vector, however it is converted into an object
  ## as returned by rcdk::load.molecules or rcdk::parse.smiles() => see below;
  ## name a character for the name of the molecule,
  ## sma a character witht the smarts string as passed onto get.depictor()
  ## ... other arguments for get.depictor()
  ##
  # Image aesthetics `depictor`
  dep <- rcdk::get.depictor(
    width = 600, height = 400,
    zoom = 6, sma = sma, ...
  )
  #
  ## load molecular types
  if (stringr::str_detect(type,stringr::regex("SMILES",ignore_case = TRUE))){
    #
    molekels <- rcdk::parse.smiles(molecules)
  }
  if (stringr::str_detect(type,stringr::regex("SDF",ignore_case = TRUE))){
    #
    ## create a list similar as in the previous case
    molekels <- list(molecules)
  }
  #
  ## molecules for the entire list
  molecules_sdf <- c()
  for (i in seq(molekels)){
    molecules_sdf[[i]] <- rcdk::view.image.2d(molekels[[i]],depictor = dep)
  }
  #
  ## Remove extra margins around the molecule
  graphics::par(mar = c(0,0,0,0))
  plot(NA,
       xlim = c(1, 10),
       ylim = c(1, 10),
       ## Remove the black bounding boxes around the molecule
       axes = F)
  #
  ## draw and annotate molecules
  for (i in seq(molekels)){
    graphics::rasterImage(molecules_sdf[[i]], 1,1, 10,10)
    graphics::text(x = 5.5,y = 1.1,deparse(substitute(molecules[[i]])))
  }
  #
}
